### ISSUE TITLE
Erreur Zend_Db_Statement_Mysqli_Exception

### ISSUE THREAD

**Issue by JBPressac** [Daniel-KM/CuratorMonitor#4]
Bonjour,
J'ai voulu tester Curator Monitor 2.4.7 avec Omeka 2.5.1 mais lorsque je clique sur le menu Curator monitor (http://localhost/omeka/admin/curator-monitor), j'obtiens une erreur:

```
> exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Invalid default value for 'added'' in /var/www/html/omeka251/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/html/omeka251/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/html/omeka251/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 [internal function]: Zend_Db_Adapter_Abstract->query('CREATE TEMPORAR...')
#3 /var/www/html/omeka251/application/libraries/Omeka/Db.php(79): call_user_func_array(Array, Array)
#4 /var/www/html/omeka251/plugins/HistoryLog/models/Table/HistoryLogChange.php(303): Omeka_Db->__call('query', Array)
#5 /var/www/html/omeka251/plugins/HistoryLog/models/Table/HistoryLogChange.php(303): Omeka_Db->query('CREATE TEMPORAR...')
#6 /var/www/html/omeka251/plugins/HistoryLog/models/Table/HistoryLogChange.php(217): Table_HistoryLogChange->_countRecordsLastChange(Array, Array, true)
#7 /var/www/html/omeka251/plugins/HistoryLog/models/Table/HistoryLogEntry.php(218): Table_HistoryLogChange->countRecords(Array, true, true, true)
#8 [internal function]: Table_HistoryLogEntry->countRecords(Array)
#9 /var/www/html/omeka251/application/controllers/helpers/Db.php(59): call_user_func_array(Array, Array)
#10 /var/www/html/omeka251/plugins/CuratorMonitor/controllers/IndexController.php(72): Omeka_Controller_Action_Helper_Db->__call('countRecords', Array)
#11 /var/www/html/omeka251/plugins/CuratorMonitor/controllers/IndexController.php(72): Omeka_Controller_Action_Helper_Db->countRecords(Array)
#12 /var/www/html/omeka251/application/libraries/Zend/Controller/Action.php(516): CuratorMonitor_IndexController->indexAction()
#13 /var/www/html/omeka251/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#14 /var/www/html/omeka251/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#15 /var/www/html/omeka251/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#16 /var/www/html/omeka251/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#17 /var/www/html/omeka251/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#18 /var/www/html/omeka251/admin/index.php(28): Omeka_Application->run()
#19 {main}
```

**Comment by Daniel-KM** [comment]
Le bug est sur [HistoryLog](https://github.com/Daniel-KM/HistoryLog), les deux plugins étant développés en parallèle pour un site. 

La page en question montre des statistiques sur l'avancement de l'édition des métadonnées à partir des éléments "Monitor" (voir l'onglet dans l'édition des items) et permet de publier en lot ceux qui sont suffisamment avancés. 

Je n'ai pas réussi à reproduire l'erreur (mais je viens de corriger deux petits bugs dans HistoryLog). Peut-être est-ce dû à la version mysql.

**Comment by Daniel-KM** [comment]
Est-ce que cela fonctionne en remplaçant dans le fichier `HistoryLog/models/Table/HistoryLogChange.php` ligne 267 :

```php
    $lastChangesColumns['added'] = "IF(MAX($aliasEntry.added)";
```

par 

```php
    $lastChangesColumns['added'] = "IFNULL(MAX($aliasEntry.added), '2001-01-01')";
```

ou


```php
    $lastChangesColumns['added'] = new Zend_Db_Expr("IFNULL(MAX($aliasEntry.added), '2001-01-01')");
```

**Comment by JBPressac** [comment]
Merci pour votre réponse. J'ai essayé les deux solutions proposées mais aucune ne fonctionne. Notez que je ne reproduis pas le problème sous Omeka 2.3.1.

**Comment by Daniel-KM** [comment]
Y-a-t-il des métadonnées de date en "0000-00-00" (dans le champ "added" de "history_logs") ?

**Comment by JBPressac** [comment]
Dans la table mySQL `omeka_history_log_entries` ? Non, il n'y en a pas.

**Comment by Daniel-KM** [comment]
Je n'arrive pas à reproduire dans Omeka 2.3.1 ou Omeka 2.5.1 sur une installation fraiche (mais j'utilise mariadb 15 et je n'ai pas mysql sous la main). En fait, l'erreur devrait se produire avec cette requête : 

```sql
CREATE TEMPORARY TABLE history_log_1 AS 
SELECT `history_log_changes`.`element_id`, `history_log_entries`.`record_type`, `history_log_entries`.`record_id`, IF (history_log_changes.type = 'delete', NULL, history_log_changes.text) AS `text`, `history_log_entries`.`added` 
FROM `omeka_history_log_changes` AS `history_log_changes`
INNER JOIN `omeka_history_log_entries` AS `history_log_entries` ON `history_log_entries`.`id` = `history_log_changes`.`entry_id` 
WHERE (`history_log_changes`.`element_id` IN (76, 77, 78, 79, 80, 81, 82, 85, 86, 87)) 
AND (`history_log_entries`.`added` >= '2017-08-24 00:00:00') 
AND (`history_log_entries`.`added` <= '2017-08-24 23:59:59.999999');

CREATE TEMPORARY TABLE history_log_2 AS 
SELECT `history_log_changes`.`element_id`, `history_log_entries`.`record_type`, `history_log_entries`.`record_id`, IFNULL(MAX(history_log_entries.added), '2001-01-01') AS `added` 
FROM `omeka_history_log_changes` AS `history_log_changes`
INNER JOIN `omeka_history_log_entries` AS `history_log_entries` ON `history_log_entries`.`id` = `history_log_changes`.`entry_id` 
WHERE (`history_log_changes`.`element_id` IN (76, 77, 78, 79, 80, 81, 82, 85, 86, 87)) 
AND (`history_log_entries`.`added` >= '2017-08-24 00:00:00') 
AND (`history_log_entries`.`added` <= '2017-08-24 23:59:59.999999') 
GROUP BY `history_log_changes`.`element_id`, `history_log_entries`.`record_type`, `history_log_entries`.`record_id`;

DROP TABLE IF EXISTS history_log_1;
DROP TABLE IF EXISTS history_log_2;
```

Je ne sais pas si le problème survient avec la première requête ou la seconde, j'ai mis les deux. Les éléments (76, 77, 78, 79, 80, 81, 82, 85, 86, 87) doivent correspondre aux ids des éléments ajoutés par le plugin CuratorMonitor. 

Si cela ne fonctionne pas, il faut m'indiquer la version de mysql. Si cela fonctionne, c'est que la requête sur votre site est différente et il faudrait récupérer la requête query qui échoue ligne 302/303.

**Comment by JBPressac** [comment]
Les tables temporaires ne sont pas créées quand j'execute le code SQL dans phpMyAdmin. J'utilise la version 5.5.57-0 de mySQL sous Debian. Je ne sais pas comment récupérer la requête ligne 302/303. Comment puis-je procéder ?

**Comment by Daniel-KM** [comment]
Les tables ne sont pas forcément visibles dans phpmyadmin et elles n'existent que le temps de la requête. 

```sql
CREATE TEMPORARY TABLE history_log_1 AS 
SELECT `history_log_changes`.`element_id`, `history_log_entries`.`record_type`, `history_log_entries`.`record_id`, IF (history_log_changes.type = 'delete', NULL, history_log_changes.text) AS `text`, `history_log_entries`.`added` 
FROM `omeka_history_log_changes` AS `history_log_changes`
INNER JOIN `omeka_history_log_entries` AS `history_log_entries` ON `history_log_entries`.`id` = `history_log_changes`.`entry_id` 
WHERE (`history_log_entries`.`added` >= '2010-08-24 00:00:00') 
AND (`history_log_entries`.`added` <= '2017-08-24 23:59:59.999999');

CREATE TEMPORARY TABLE history_log_2 AS 
SELECT `history_log_changes`.`element_id`, `history_log_entries`.`record_type`, `history_log_entries`.`record_id`, IFNULL(MAX(history_log_entries.added), '2001-01-01') AS `added` 
FROM `omeka_history_log_changes` AS `history_log_changes`
INNER JOIN `omeka_history_log_entries` AS `history_log_entries` ON `history_log_entries`.`id` = `history_log_changes`.`entry_id` 
WHERE (`history_log_entries`.`added` >= '2010-08-24 00:00:00') 
AND (`history_log_entries`.`added` <= '2017-08-24 23:59:59.999999') 
GROUP BY `history_log_changes`.`element_id`, `history_log_entries`.`record_type`, `history_log_entries`.`record_id`;

# puis tester.
SELECT * FROM history_log_1;
SELECT * FROM history_log_2;

DROP TABLE IF EXISTS history_log_1;
DROP TABLE IF EXISTS history_log_2;
```

L'essentiel est que les tables temporaires aient pu être créées et supprimées sans erreur, ce qui semblent le cas. Donc l'erreur vient d'ailleurs, mais je ne vois pas où. Pour avoir la requête, il faut modifier la config dans `application/config/config.ini` (`log.errors = true`, `log.priority = Zend_Log::DEBUG`, et `log.sql = true`), et/ou ajouter `debug($query);` dans la boucle.

C'est sans doute lié à la base elle-même, à des colonnes added qui n'ont pas été mises à jour ou à autre chose (cf. sur le forum notamment https://forum.omeka.org/t/migrating-omeka-to-php7-and-mysql-5-7-16/2173).
